# Generated by Django 4.1 on 2023-01-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('username', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
