# Generated by Django 4.1 on 2023-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_loginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='username',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
