# Generated by Django 4.1 on 2023-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('type_notification', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push')], max_length=5)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receiver_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('receivers_mobiles', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
