# Generated by Django 4.1 on 2022-08-31 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('grand_father', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_grand_father', to='family.grandfather')),
                ('grand_mather', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_grand_mather', to='family.grandmother')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=50, verbose_name='gender')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_person', to='family.father')),
                ('mather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mather_person', to='family.mather')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreatGrandMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='great_grand_mother_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreatGrandFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='great_grand_father_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grandmother',
            name='great_grand_father',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_great_grand_father', to='family.greatgrandfather'),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='great_grand_mather',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='matter_mather_grand_mather', to='family.greatgrandmother'),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='grand_mather_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='great_grand_father',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_great_grand_father', to='family.greatgrandfather'),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='great_grand_mather',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_mather_grand_mather', to='family.greatgrandmother'),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='grand_father_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='father',
            name='grand_father',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_grand_father', to='family.grandfather'),
        ),
        migrations.AddField(
            model_name='father',
            name='grand_mather',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_grand_mather', to='family.grandmother'),
        ),
        migrations.AddField(
            model_name='father',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
