# Generated by Django 4.1 on 2022-09-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='father',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greatgrandfather',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greatgrandmother',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mather',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('father', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_wife', to='family.father')),
                ('mather', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_wife', to='family.mather')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_wife', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('father', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_husband', to='family.father')),
                ('mather', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_husband', to='family.mather')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_husband', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='husband',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='person_husband', to='family.husband'),
        ),
        migrations.AddField(
            model_name='person',
            name='wife',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='person_wife', to='family.wife'),
        ),
    ]
