# Generated by Django 4.1 on 2022-09-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_father_hidden_grandfather_hidden_grandmother_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grandfather',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grandmother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='greatgrandfather',
            options={},
        ),
        migrations.AlterModelOptions(
            name='greatgrandmother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mather',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={},
        ),
        migrations.RemoveField(
            model_name='father',
            name='created',
        ),
        migrations.RemoveField(
            model_name='father',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='grandfather',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grandfather',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='grandmother',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grandmother',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='greatgrandfather',
            name='created',
        ),
        migrations.RemoveField(
            model_name='greatgrandfather',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='greatgrandmother',
            name='created',
        ),
        migrations.RemoveField(
            model_name='greatgrandmother',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='husband',
            name='created',
        ),
        migrations.RemoveField(
            model_name='husband',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='mather',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mather',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='wife',
            name='created',
        ),
        migrations.RemoveField(
            model_name='wife',
            name='modified',
        ),
        migrations.AddField(
            model_name='father',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='father',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grandfather',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grandmother',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='greatgrandfather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='greatgrandfather',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='greatgrandmother',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='greatgrandmother',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='husband',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='husband',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mather',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wife',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wife',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='grandfather',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='grandmother',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='greatgrandfather',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='greatgrandmother',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='husband',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mather',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wife',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
