# Generated by Django 4.1 on 2022-09-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0003_alter_father_options_alter_grandfather_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=150, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='husband',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_information_husband', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wife',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_wife_information', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='father',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='father_user_information', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='grandfather',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='grand_father_user_information', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='grandmother',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='grand_mather_user_information', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='greatgrandfather',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='great_grand_father_user_information', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='greatgrandmother',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='great_grand_mother_user_information', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='mather',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mather_user_information', to='family.userinformation'),
        ),
    ]
