# Generated by Django 4.1 on 2022-09-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_userinformation_alter_husband_user_alter_wife_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husband',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_information_husband', to='family.userinformation'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_wife_information', to='family.userinformation'),
        ),
    ]
