# Generated by Django 4.1 on 2023-03-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_father_created_by_father_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarriageRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('marriage_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.DateTimeField(auto_now=True, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='grandfather',
            name='great_grand_father',
        ),
        migrations.RemoveField(
            model_name='grandfather',
            name='great_grand_mather',
        ),
        migrations.RemoveField(
            model_name='grandfather',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grandmother',
            name='great_grand_father',
        ),
        migrations.RemoveField(
            model_name='grandmother',
            name='great_grand_mather',
        ),
        migrations.RemoveField(
            model_name='grandmother',
            name='user',
        ),
        migrations.RemoveField(
            model_name='greatgrandfather',
            name='user',
        ),
        migrations.RemoveField(
            model_name='greatgrandmother',
            name='user',
        ),
        migrations.RemoveField(
            model_name='husband',
            name='father',
        ),
        migrations.RemoveField(
            model_name='husband',
            name='mather',
        ),
        migrations.RemoveField(
            model_name='husband',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mather',
            name='grand_father',
        ),
        migrations.RemoveField(
            model_name='mather',
            name='grand_mather',
        ),
        migrations.RemoveField(
            model_name='mather',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wife',
            name='father',
        ),
        migrations.RemoveField(
            model_name='wife',
            name='mather',
        ),
        migrations.RemoveField(
            model_name='wife',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.RemoveField(
            model_name='person',
            name='husband',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mather',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wife',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Father',
        ),
        migrations.DeleteModel(
            name='GrandFather',
        ),
        migrations.DeleteModel(
            name='GrandMother',
        ),
        migrations.DeleteModel(
            name='GreatGrandFather',
        ),
        migrations.DeleteModel(
            name='GreatGrandMother',
        ),
        migrations.DeleteModel(
            name='Husband',
        ),
        migrations.DeleteModel(
            name='Mather',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
        migrations.DeleteModel(
            name='Wife',
        ),
        migrations.AddField(
            model_name='parentchildrelationship',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='family.person'),
        ),
        migrations.AddField(
            model_name='parentchildrelationship',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='family.person'),
        ),
        migrations.AddField(
            model_name='marriagerelationship',
            name='spouse_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marriages_1', to='family.person'),
        ),
        migrations.AddField(
            model_name='marriagerelationship',
            name='spouse_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marriages_2', to='family.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
    ]
